language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
  include:
    - { python: "3.7", dist: xenial, sudo: true }
install:
  - pip install flake8 nose==1.3.0 flask flask_restful flask_restplus injector flask_sqlalchemy eventlet typing mypy typed_ast
script:
  - make ci
